### ISSUE TITLE
Configurable actions in the ui

### ISSUE THREAD

**Issue by pbroman** [tuub/kitodo-mediaserver#141]
It would be nice to have the possibility to add actions to the ui simply by configuration, as is the case with the importer. Similarily with the config importer.actionsBeforeIndexing (e.g.), there should be a config for the ui simply listing action bean names and possibly params.

**Comment by ponchofiesta** [comment]
You can now define actions like this in the UI:
```yaml
ui:
  works:
    actions:
      cacheclear:
        label: Clear derivatives cache
        action: cacheDeleteAction
        enabled: true
        parameters:
      reindex:
        label: Reindex in Viewer
        action: viewerIndexingAction
        enabled: true
        parameters:
```
These two actions are enabled by default. You can disable an action this way:
```yaml
ui:
  works:
    actions:
      reindex:
        enabled: false
```

I wanted to use a List instead of a Map but than you can not choose a specific action from default.yml in your local.yml. The key names do not matter.
